apiVersion: v1
kind: Service
metadata:
  name: configmap-sidecar-container
spec:
  type: LoadBalancer
  ports:
    - name: demo-site1
      port: 8001
      targetPort: 8001
      protocol: TCP
    - name: demo-site2
      port: 8002
      targetPort: 8002
      protocol: TCP
    - name: demo-site3
      port: 8003
      targetPort: 8003
      protocol: TCP
  selector:
    app.kubernetes.io/name: configmap-sidecar-container